### ISSUE TITLE
So that visual design team members can get set up with common practices and rituals faster, create an onboarding checklist

### ISSUE THREAD

**Issue by amberwreed** [18F/visual-design#20]
Create a list of important things to know about related to the visual design team on the wiki.

**Comment by jenniferthibault** [comment]
We may want to check the handbook first to see what, if anything, exists already

**Comment by amberwreed** [comment]
Next steps:
- [ ] Talking to visual design team "looking back at what you know now, what do you wish you knew when you started."
- [ ] Create a list of visual design link and or best practices
- [ ] Submit to the handbook

**Comment by jenniferthibault** [comment]
We did this in a google doc! 🎉 
🔒 [Visual Design Welcome Guide](https://docs.google.com/document/d/1M43o66GeNez7KC3G4nG0LDBw7gJIaK7hqvX9cV9rXYI/edit#heading=h.qa2gw4i59b9m)
